version: "3"

services:
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front
    tty: true

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: "yarn start"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
